"""fix missing scraper_name columns

Revision ID: e905ab7993c4
Revises: 66c2ec769424
Create Date: 2026-01-24 01:55:03.776327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e905ab7993c4'
down_revision: Union[str, Sequence[str], None] = '66c2ec769424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackcluded_items', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Retail'"))
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('validation_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'VALIDATED'"))
        batch_op.alter_column('anomaly_flags',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('kaizen_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraper_name', sa.String(), nullable=True))
        batch_op.drop_index('ix_kaizen_insights_spider_name')
        batch_op.create_index(batch_op.f('ix_kaizen_insights_scraper_name'), ['scraper_name'], unique=False)
        batch_op.drop_column('spider_name')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expiry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bids_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_left_raw', sa.String(), nullable=True))
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'retail'"))
        batch_op.alter_column('validation_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'VALIDATED'"))
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('opportunity_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_offers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_shop_name'), ['shop_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_url'), ['url'], unique=False)
        batch_op.drop_column('origin_category')

    with op.batch_alter_table('pending_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expiry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bids_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_left_raw', sa.String(), nullable=True))
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'retail'"))
        batch_op.alter_column('validation_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.alter_column('is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('opportunity_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('origin_category')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_snapshot', sa.Boolean(), nullable=True))

    with op.batch_alter_table('scraper_execution_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraper_name', sa.String(), nullable=True))
        batch_op.drop_index('ix_scraper_execution_logs_spider_name')
        batch_op.create_index(batch_op.f('ix_scraper_execution_logs_scraper_name'), ['scraper_name'], unique=False)
        batch_op.drop_column('spider_name')

    with op.batch_alter_table('scraper_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraper_name', sa.String(), nullable=True))
        batch_op.drop_column('spider_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.add_column('scraper_status', sa.Column('spider_name', sa.VARCHAR(), nullable=False))
    op.drop_column('scraper_status', 'scraper_name')
    op.add_column('scraper_execution_logs', sa.Column('spider_name', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_scraper_execution_logs_scraper_name'), table_name='scraper_execution_logs')
    op.create_index(op.f('ix_scraper_execution_logs_spider_name'), 'scraper_execution_logs', ['spider_name'], unique=False)
    op.drop_column('scraper_execution_logs', 'scraper_name')
    op.drop_column('price_history', 'is_snapshot')
    op.add_column('pending_matches', sa.Column('origin_category', sa.VARCHAR(length=20), server_default=sa.text("'retail'"), nullable=True))
    op.alter_column('pending_matches', 'opportunity_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pending_matches', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.alter_column('pending_matches', 'validation_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('pending_matches', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'retail'"))
    op.drop_column('pending_matches', 'time_left_raw')
    op.drop_column('pending_matches', 'bids_count')
    op.drop_column('pending_matches', 'expiry_at')
    op.drop_column('pending_matches', 'sale_type')
    op.add_column('offers', sa.Column('origin_category', sa.VARCHAR(length=20), server_default=sa.text("'retail'"), nullable=True))
    op.drop_index(op.f('ix_offers_url'), table_name='offers')
    op.drop_index(op.f('ix_offers_shop_name'), table_name='offers')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.alter_column('offers', 'opportunity_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('offers', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.alter_column('offers', 'validation_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'VALIDATED'"))
    op.alter_column('offers', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'retail'"))
    op.drop_column('offers', 'time_left_raw')
    op.drop_column('offers', 'bids_count')
    op.drop_column('offers', 'expiry_at')
    op.drop_column('offers', 'sale_type')
    op.add_column('kaizen_insights', sa.Column('spider_name', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_kaizen_insights_scraper_name'), table_name='kaizen_insights')
    op.create_index(op.f('ix_kaizen_insights_spider_name'), 'kaizen_insights', ['spider_name'], unique=False)
    op.drop_column('kaizen_insights', 'scraper_name')
    op.drop_index(op.f('ix_collection_items_product_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_owner_id'), table_name='collection_items')
    op.alter_column('blackcluded_items', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.alter_column('blackcluded_items', 'anomaly_flags',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('blackcluded_items', 'validation_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'VALIDATED'"))
    op.alter_column('blackcluded_items', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blackcluded_items', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Retail'"))
    # ### end Alembic commands ###
