import os
import sys
from pathlib import Path

"""
🛡️ 3OX-ARCHITECT V2: FULL KERNEL INITIALIZER (T3 SPEC)
-----------------------------------------------------
Version: 2.0.0 (Sirius Compliant)
Purpose: Initialize a 100% compliant 3OX Agent with Kernel-style architecture.
Implements the 7 core files and the vec3 protected surfaces.
"""

# 3OX Core 7-File Structure
CORE_7_FILES = {
    "sparkfile.md": "# 🧠 AGENT SPECIFICATION\nRole: Universal 3OX Agent\nKernel: vec3/v1\n\n## Core Directives\n- Assess before Plan\n- Verify before Log",
    "brain.rs": "/* 3OX Brain Config - Compiles to brain.exe */\nfn main() {\n    println!(\"3OX Kernel Initialized\");\n}",
    "tools.yml": "# 🛠️ Tool Registry\ntools:\n  - name: system_query\n    description: Read system state",
    "routes.json": "{\n  \"operations\": { \"default\": \"log_activity\" }\n}",
    "limits.json": "{\n  \"max_memory\": \"512MB\",\n  \"max_execution_time\": \"300s\"\n}",
    "run.rb": "# 3OX Ruby Runtime\nputs '3OX Runtime Active'",
    "3ox.log": "⧗-25.133 [KERNEL] 3OX System Seeded."
}

# vec3 Kernel Surfaces
VEC3_STRUCTURE = {
    "vec3": {
        "rc": {
            "rules.ref": "# Immutable Behavior Rules\n1. Protect System Integrity\n2. Log every operation",
            "sys.ref": "# System Control Knobs\nDEBUG_MODE=true"
        },
        "lib": {
            "architecture.ref": "# Read-only Reference Library\nStandard: Clean Architecture Layered"
        },
        "dev": {
            "bridges": ["__init__.py"],
            "adapters": ["__init__.py"]
        },
        "var": {
            "receipts": [],
            "events": [],
            "inflight": [],
            "status.ref": "READY"
        }
    }
}

# Standard Clean Architecture (Src) still included as the Payload structure
APP_STRUCTURE = {
    "src": {
        "domain": ["models.py", "schemas.py"],
        "application": ["use_cases.py"],
        "infrastructure": ["database.py", "repositories.py"],
        "interfaces": ["api.py", "web.py"]
    }
}

def create_files(base_path, files_dict):
    for name, content in files_dict.items():
        file_path = os.path.join(base_path, name)
        if not os.path.exists(file_path):
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Generated Core File: {file_path}")

def create_folders(base_path, structure):
    for name, content in structure.items():
        current_path = os.path.join(base_path, name)
        os.makedirs(current_path, exist_ok=True)
        if isinstance(content, dict):
            create_folders(current_path, content)
        elif isinstance(content, list):
            for file_name in content:
                file_path = os.path.join(current_path, file_name)
                if not os.path.exists(file_path):
                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write(f"# {name} Reference")
                    print(f"Generated Path: {file_path}")

def init_3ox_agent():
    print("3OX.BUILDER: Deploying Full Kernel (T3)...")
    root = os.getcwd()
    
    # 1. Create 7 Core Files
    create_files(root, CORE_7_FILES)
    
    # 2. Create vec3 structure
    create_folders(root, VEC3_STRUCTURE)
    
    # 3. Create App logic (Clean Architecture)
    create_folders(root, APP_STRUCTURE)
    
    # 4. Global files
    globals = {
        ".env": "PROJECT_TIER=T3\nDEBUG=True",
        "requirements.txt": "sqlalchemy\npydantic\nalembic",
        "README.md": "# 3OX Agent Project\nGenerated by 3OX-Architect V2."
    }
    create_files(root, globals)

    print("\n[OK] T3 Kernel initialized successfully.")
    print("Structure: 7 Core Files + vec3 Protected Surfaces.")
    print("Operational Loop Configured: Assess -> Plan -> Execute -> Verify -> Log.")

if __name__ == "__main__":
    init_3ox_agent()
